title: cat webring
description: just a webring for cat owners, cat enjoyers, people who write about cats, or are cats. cats after cats after cats!!!!
url:  
repository: jackpurrin/ring
remote_theme: pages-themes/minimal@v0.2.0
feed:
plugins:
  -  jekyll-remote-theme
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/